name: WikiSearch Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  builds:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Create Work Dir
        run: mkdir build
      - name: Configure
        working-directory: ./build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: Build
        working-directory: ./build
        run: cmake --build . --config Release
