# Workflow for building the project and publishing executable file.
name: WikiSearch Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build directory
      run: mkdir build && cd build

    - name: Configure CMake
      run: cmake -G "MinGW Makefiles" ..

    - name: Build
      run: cmake --build .
